// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNSFYO_SH0K-o-cJ8Vmz8PdXLomPJs1fQ',
    appId: '1:402018636829:web:116369fbad2b82167ce2f4',
    messagingSenderId: '402018636829',
    projectId: 'to-do-9819b',
    authDomain: 'to-do-9819b.firebaseapp.com',
    storageBucket: 'to-do-9819b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuOfE147rsHcyFVp3mte-7Mj5uhldHP54',
    appId: '1:402018636829:android:b26352e9b298bac87ce2f4',
    messagingSenderId: '402018636829',
    projectId: 'to-do-9819b',
    storageBucket: 'to-do-9819b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2oejwB0jaGVlZIaul8Z-Kwqt3I9SSpE',
    appId: '1:402018636829:ios:4c4b1c4dca6d54447ce2f4',
    messagingSenderId: '402018636829',
    projectId: 'to-do-9819b',
    storageBucket: 'to-do-9819b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2oejwB0jaGVlZIaul8Z-Kwqt3I9SSpE',
    appId: '1:402018636829:ios:4c4b1c4dca6d54447ce2f4',
    messagingSenderId: '402018636829',
    projectId: 'to-do-9819b',
    storageBucket: 'to-do-9819b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNSFYO_SH0K-o-cJ8Vmz8PdXLomPJs1fQ',
    appId: '1:402018636829:web:abf0aef4ddd9b96f7ce2f4',
    messagingSenderId: '402018636829',
    projectId: 'to-do-9819b',
    authDomain: 'to-do-9819b.firebaseapp.com',
    storageBucket: 'to-do-9819b.appspot.com',
  );
}
